galaxy_info:
  author: Remo Mattei
  description: Pure Post Configuration
  company: Avast

  license: Apache


  # platforms:
  # - name: Centos 7

dependencies: []
  # To be able to get to github in order to download the pure repo.
